-- 品牌数据表初始化脚本
-- 如果表不存在则创建
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'brands')
BEGIN
    CREATE TABLE brands (
        BrandId INT IDENTITY(1,1) PRIMARY KEY,
        BrandName NVARCHAR(200) NOT NULL,
        BrandLogo NVARCHAR(500) NULL,
        BrandDesc NVARCHAR(500) NULL,
        SortOrder INT DEFAULT 0,
        Status INT DEFAULT 1,
        CreateTime DATETIME DEFAULT GETDATE()
    )
END

-- 删除现有数据（重新初始化）
DELETE FROM brands

-- 插入品牌数据（从电子元器件选型系统提取）
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('FOJAN(富捷)', 1, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('UNI-ROYAL(厚声)', 2, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('SAMSUNG(三星)', 3, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('HRK(鸿瑞凯电子)', 4, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('YAGEO(国巨)', 5, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('MURATA(村田)', 6, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('FENGHUA(风华高科)', 7, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('TORCH(火炬电子)', 8, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('HONGYUAN(鸿远电子)', 9, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('HONGDA(宏达电子)', 10, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('SANHUAN(三环集团)', 11, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('SUNLORD(顺络电子)', 12, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('AIHUA(艾华集团)', 13, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('FARATRONIC(法拉电子)', 14, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('JIANGHAI(江海股份)', 15, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('YUYANG(宇阳科技)', 16, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('CCTC(潮州三环)', 17, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('TECSTAR(台星)', 18, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('WALTER(华德电子)', 19, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('EVER(亿能电子)', 20, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('TA-I-CN(大毅科技大陆)', 21, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('ROYALOHM-CN(厚生大陆)', 22, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('VIKING-CN(光颉科技大陆)', 23, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('TTC-CN(台湾电阻大陆)', 24, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('PSA-CN(信昌电陶大陆)', 25, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('TDK-CN(TDK中国)', 26, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('MURATA-CN(村田中国)', 27, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('SAMSUNG-CN(三星中国)', 28, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('AVX-CN(AVX中国)', 29, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('VISHAY-CN(威世中国)', 30, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('KEMET-CN(基美中国)', 31, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('BOURNS-CN(伯恩斯中国)', 32, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('HRE(芯声)', 33, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('PANASONIC-CN(松下中国)', 34, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('KYOCERA-CN(京瓷中国)', 35, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('AISHI(艾华)', 36, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('SUNTAN(日电导)', 37, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('KINJI(金积)', 38, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('UNIOHM(厚声)', 39, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('RALEC(旺诠)', 40, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('TAITEK(泰铭)', 41, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('SINOCARTA(华瓷)', 42, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('CHINOCERA(中瓷)', 43, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('SUSUMU-CN(进工业中国)', 44, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('KOA-CN(KOA中国)', 45, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('WALSIN-TW(华新科)', 46, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('YAGEO-TW(国巨台湾)', 47, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('TA-I-TW(大毅台湾)', 48, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('VIKING-TW(光颉台湾)', 49, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('ROYALOHM-TW(厚生台湾)', 50, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('TTC-TW(台湾电阻台湾)', 51, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('HUIJU(汇聚)', 52, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('PSH(信昌电陶台湾)', 53, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('HOLYSTONE(禾伸堂)', 54, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('TDK-TW(TDK台湾)', 55, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('MURATA-TW(村田台湾)', 56, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('AVX-TW(AVX台湾)', 57, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('KEMET-TW(基美台湾)', 58, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('VISHAY-TW(威世台湾)', 59, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('BOURNS-TW(伯恩斯台湾)', 60, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('LITTELFUSE-TW(力特台湾)', 61, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('SAMSUNG-TW(三星台湾)', 62, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('PANASONIC-TW(松下台湾)', 63, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('MURATA-JP(村田日本)', 64, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('TDK-JP(TDK日本)', 65, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('TAIYO(太阳诱电)', 66, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('KYOCERA(京瓷)', 67, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('PANASONIC(松下)', 68, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('SANYO(三洋)', 69, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('RUBYCON(红宝石)', 70, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('NICHICON(尼吉康)', 71, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('CHEMI-CON(贵弥功)', 72, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('ELNA(依娜)', 73, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('NIPPON(日本化工)', 74, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('NCC(日本贵弥功)', 75, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('DARFON(达方)', 76, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('GYZ(昀冢科技)', 77, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('SAMWHA(三和)', 78, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('OKAYA(冈谷)', 79, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('SAMSUNG-KR(三星电机韩国)', 80, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('SEMCO(三星电机)', 81, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('KEMET-KR(基美韩国)', 82, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('AVX(AVX)', 83, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('Knowles(楼氏)', 84, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('JOHANSON(约翰逊)', 85, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('MEGSINE(兆讯)', 86, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('VISHAY(威世)', 87, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('KEMET(基美)', 88, 1)
INSERT INTO brands (BrandName, SortOrder, Status) VALUES ('BOURNS(伯恩斯)', 89, 1)

SELECT COUNT(*) AS TotalBrands FROM brands
